# Generated by Django 5.2.17 on 2026-08-16 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='用例名称')),
                ('recording_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='来源录制 ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='POM pytest 脚本全文')),
                ('source', models.CharField(choices=[('ai_normalized', 'AI 重组'), ('manual', '手动创建')], db_index=True, default='ai_normalized', max_length=32, verbose_name='来源')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪'), ('archived', '归档')], db_index=True, default='ready', max_length=16, verbose_name='状态')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'UI 用例',
                'verbose_name_plural': 'UI 用例',
                'db_table': 'ui_test_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recording_id', 'source'], name='ui_test_cas_recordi_7c21e1_idx')],
            },
        ),
    ]
