# Generated by Django 5.2.17 on 2026-08-16 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='实例名称')),
                ('runtime_dir', models.CharField(blank=True, default='', max_length=512, verbose_name='运行时目录')),
                ('dsh_bin_path', models.CharField(blank=True, default='', max_length=512, verbose_name='dsh 二进制路径')),
                ('home_dir', models.CharField(blank=True, default='', max_length=512, verbose_name='DSH_HOME 目录')),
                ('version', models.CharField(blank=True, default='', max_length=64, verbose_name='DSH 版本')),
                ('node_version', models.CharField(blank=True, default='', max_length=64, verbose_name='Node.js 版本')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('healthy', '健康'), ('warning', '警告'), ('error', '异常')], db_index=True, default='unknown', max_length=16, verbose_name='状态')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='是否默认')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '运行时实例',
                'verbose_name_plural': '运行时实例',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
