# Generated by Django 5.2.17 on 2026-08-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('volcark', '火山方舟 Ark'), ('openai_compatible', 'OpenAI 兼容接口'), ('ollama', 'Ollama'), ('custom', '自定义')], db_index=True, max_length=32, verbose_name='提供方')),
                ('base_url', models.CharField(blank=True, default='', max_length=256, verbose_name='Base URL')),
                ('model_name', models.CharField(max_length=128, verbose_name='模型名')),
                ('api_key_encrypted', models.TextField(blank=True, default='', verbose_name='API Key 密文')),
                ('api_key_mask', models.CharField(blank=True, default='', max_length=64, verbose_name='API Key 掩码')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='默认配置')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='temperature/max_tokens 等', verbose_name='扩展参数')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'verbose_name_plural': 'AI 模型配置',
                'db_table': 'ai_provider_configs',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
