# Generated by Django 5.2.17 on 2026-08-16 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='参数集名称')),
                ('values', models.JSONField(blank=True, default=dict, help_text='键值对字典。secret 键的明文在 P1 阶段直接入库，P3 加密。', verbose_name='参数值')),
                ('secret_keys', models.JSONField(blank=True, default=list, help_text='values 中哪些 key 是 secret，序列化时会脱敏为 ${secret:<key>}', verbose_name='Secret 键列表')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '参数集',
                'verbose_name_plural': '参数集',
                'db_table': 'testdata_parameter_sets',
                'ordering': ['-created_at'],
            },
        ),
    ]
