# Generated by Django 5.2.17 on 2026-08-16 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='录制名称')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], db_index=True, default='python', max_length=16, verbose_name='语言')),
                ('framework', models.CharField(choices=[('playwright', 'Playwright'), ('selenium', 'Selenium')], db_index=True, default='playwright', max_length=16, verbose_name='框架')),
                ('start_url', models.CharField(blank=True, default='', max_length=512, verbose_name='起始 URL')),
                ('raw_content', models.TextField(verbose_name='原始脚本内容')),
                ('normalized_content', models.TextField(blank=True, default='', verbose_name='归一化脚本内容')),
                ('locators_count', models.IntegerField(default=0, verbose_name='定位器数量')),
                ('actions_count', models.IntegerField(default=0, verbose_name='动作数量')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='解析警告')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '录制脚本',
                'verbose_name_plural': '录制脚本',
                'ordering': ['-created_at'],
            },
        ),
    ]
