# Generated by Django 5.2.17 on 2026-08-16 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='任务集名称')),
                ('recording_id', models.IntegerField(db_index=True, verbose_name='录制 ID')),
                ('correlation_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='跨系统 ID 关联链的起点（recorder → replay → asset → testdata …）', unique=True, verbose_name='关联链 UUID')),
                ('status', models.CharField(choices=[('created', '已创建'), ('replaying', '回放中'), ('replay_done', '回放完成'), ('failed', '失败')], db_index=True, default='created', max_length=32, verbose_name='状态')),
                ('current_stage', models.CharField(blank=True, default='', max_length=64, verbose_name='当前阶段')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '任务集',
                'verbose_name_plural': '任务集',
                'db_table': 'tasksets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('stage', models.CharField(choices=[('replay', '回放'), ('extract', '抽取'), ('design', '设计'), ('generate', '生成')], db_index=True, max_length=32, verbose_name='阶段')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='running', max_length=16, verbose_name='状态')),
                ('external_ref', models.CharField(blank=True, default='', help_text="如 'replay:12'，关联 replay 那边的 ReplayRun", max_length=256, verbose_name='外部引用')),
                ('detail', models.JSONField(blank=True, default=dict, help_text='duration / steps / trace_hash 等执行数据', verbose_name='详细信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('task_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_jobs', to='tasksets.taskset', verbose_name='所属任务集')),
            ],
            options={
                'verbose_name': '阶段作业',
                'verbose_name_plural': '阶段作业',
                'db_table': 'taskset_stage_jobs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task_set', 'stage'], name='taskset_sta_task_se_1644b0_idx'), models.Index(fields=['task_set', 'status'], name='taskset_sta_task_se_1cd290_idx')],
            },
        ),
    ]
