# Generated by Django 5.2.17 on 2026-08-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskset',
            name='status',
            field=models.CharField(choices=[('created', '已创建'), ('replaying', '回放中'), ('replay_done', '回放完成'), ('extracting', '抽取中'), ('extract_done', '抽取完成'), ('designing', '设计中'), ('design_done', '设计完成'), ('failed', '失败')], db_index=True, default='created', max_length=32, verbose_name='状态'),
        ),
    ]
