# Generated by Django 5.2.17 on 2026-08-16 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksets', '0002_alter_taskset_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagejob',
            name='stage',
            field=models.CharField(choices=[('replay', '回放'), ('extract', '抽取'), ('design', '设计'), ('review', '评审'), ('generate', '生成')], db_index=True, max_length=32, verbose_name='阶段'),
        ),
        migrations.AlterField(
            model_name='taskset',
            name='status',
            field=models.CharField(choices=[('created', '已创建'), ('replaying', '回放中'), ('replay_done', '回放完成'), ('extracting', '抽取中'), ('extract_done', '抽取完成'), ('designing', '设计中'), ('design_done', '设计完成'), ('reviewing', '评审中'), ('review_done', '评审通过'), ('generating', '生成中'), ('generate_done', '生成完成'), ('failed', '失败')], db_index=True, default='created', max_length=32, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='GeneratedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('task_set_id', models.IntegerField(db_index=True, verbose_name='任务集 ID')),
                ('invocation_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='关联调用 ID')),
                ('script_file', models.CharField(blank=True, default='', max_length=256, verbose_name='脚本文件名')),
                ('script_content', models.TextField(blank=True, default='', verbose_name='脚本全文')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='运行报告')),
                ('status', models.CharField(choices=[('pass', '通过'), ('fail', '失败')], db_index=True, default='fail', max_length=16, verbose_name='状态')),
                ('rounds', models.IntegerField(default=0, verbose_name='自修复轮数')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('stage_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_runs', to='tasksets.stagejob', verbose_name='所属阶段作业')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '生成运行',
                'verbose_name_plural': '生成运行',
                'db_table': 'taskset_generated_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_set_id', 'status'], name='taskset_gen_task_se_9ab025_idx')],
            },
        ),
    ]
