# Generated by Django 5.2.17 on 2026-08-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksets', '0003_alter_stagejob_stage_alter_taskset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskset',
            name='cancel_requested',
            field=models.BooleanField(db_index=True, default=False, help_text='P4：协作式取消标志--流水线在阶段间检查，当前阶段跑完后停止', verbose_name='已请求终止'),
        ),
    ]
