# Generated by Django 5.2.17 on 2026-08-16 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='页面名称')),
                ('url_pattern', models.CharField(help_text='支持 {param} 占位，如 /users/{user_id}/profile', max_length=512, verbose_name='URL 模式')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '页面对象',
                'verbose_name_plural': '页面对象',
                'db_table': 'asset_repo_pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='元素名称')),
                ('role', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ARIA 角色')),
                ('candidates', models.JSONField(blank=True, default=list, help_text='数组：[{type, value, priority, robustness}]，type ∈ role/text/label/placeholder/testid/css/xpath/aria_ref', verbose_name='定位器候选')),
                ('snapshot_hash', models.CharField(blank=True, db_index=True, default='', help_text='元素视觉/结构快照的哈希，用于跨页复用匹配', max_length=128, verbose_name='快照哈希')),
                ('source', models.CharField(choices=[('recording', '录制生成'), ('manual', '手工维护'), ('api', 'API 写入')], db_index=True, default='manual', max_length=32, verbose_name='来源')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='asset_repo.pageobject', verbose_name='所属页面')),
            ],
            options={
                'verbose_name': '页面元素',
                'verbose_name_plural': '页面元素',
                'db_table': 'asset_repo_elements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pageobject',
            index=models.Index(fields=['name'], name='asset_repo__name_dbc99e_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['page', 'name'], name='asset_repo__page_id_760162_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['page', 'role'], name='asset_repo__page_id_4d9b37_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['snapshot_hash'], name='asset_repo__snapsho_747bc5_idx'),
        ),
    ]
