# Generated by Django 5.2.17 on 2026-08-16 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('stage', models.CharField(db_index=True, help_text='如 pom_extract / matrix_design', max_length=64, verbose_name='阶段')),
                ('task_set_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='任务集 ID')),
                ('recording_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='录制 ID')),
                ('instruction', models.TextField(verbose_name='指令文本')),
                ('instruction_sha', models.CharField(db_index=True, max_length=64, verbose_name='指令 SHA256')),
                ('output_text', models.TextField(blank=True, default='', verbose_name='输出文本')),
                ('parsed_json', models.JSONField(blank=True, null=True, verbose_name='解析 JSON')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('error', '错误')], db_index=True, max_length=16, verbose_name='状态')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('mock', models.BooleanField(db_index=True, default=False, verbose_name='是否 Mock')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'Agent 调用记录',
                'verbose_name_plural': 'Agent 调用记录',
                'db_table': 'agent_runtime_invocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage', 'status'], name='agent_runti_stage_7374ef_idx'), models.Index(fields=['task_set_id', 'stage'], name='agent_runti_task_se_08f555_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtifactDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('task_set_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='任务集 ID')),
                ('kind', models.CharField(choices=[('pom', 'POM 页面对象模型'), ('matrix', '场景矩阵')], db_index=True, max_length=16, verbose_name='类型')),
                ('content', models.JSONField(verbose_name='内容')),
                ('schema_version', models.CharField(default='0.1.0', max_length=32, verbose_name='契约版本')),
                ('valid', models.BooleanField(db_index=True, default=False, verbose_name='是否通过契约校验')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='校验错误列表')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='draft', max_length=16, verbose_name='评审状态')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='评审备注')),
                ('invocation_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='关联调用 ID')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='评审时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '产物草案',
                'verbose_name_plural': '产物草案',
                'db_table': 'agent_runtime_drafts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='agent_runti_kind_b96c23_idx'), models.Index(fields=['task_set_id', 'kind'], name='agent_runti_task_se_ecaec3_idx')],
            },
        ),
    ]
