# Generated by Django 5.2.17 on 2026-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinvocation',
            name='workspace_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='工作区路径'),
        ),
        migrations.AlterField(
            model_name='agentinvocation',
            name='stage',
            field=models.CharField(db_index=True, help_text='如 a1_extract / a2_design / a3_review / a4_generate', max_length=64, verbose_name='阶段'),
        ),
        migrations.AlterField(
            model_name='artifactdraft',
            name='kind',
            field=models.CharField(choices=[('pom', 'POM 页面对象模型'), ('matrix', '场景矩阵'), ('review', 'A3 评审报告')], db_index=True, max_length=16, verbose_name='类型'),
        ),
    ]
