# Generated by Django 5.2.17 on 2026-08-16 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('task_set_id', models.IntegerField(blank=True, null=True, verbose_name='关联任务集 ID')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='running', max_length=16, verbose_name='状态')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时（毫秒）')),
                ('steps_total', models.IntegerField(default=0, verbose_name='总步骤数')),
                ('steps_passed', models.IntegerField(default=0, verbose_name='通过步骤数')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('trace_path', models.CharField(blank=True, default='', max_length=512, verbose_name='Trace 文件路径')),
                ('trace_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='Trace 文件哈希')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_runs', to='recorder.recording', verbose_name='关联录制')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '回放执行',
                'verbose_name_plural': '回放执行',
                'ordering': ['-created_at'],
            },
        ),
    ]
