# Generated by Django 5.2.17 on 2026-08-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replayrun',
            name='video_path',
            field=models.CharField(blank=True, default='', help_text='P4：Playwright 录像（webm），页面级查看用', max_length=512, verbose_name='回放视频路径'),
        ),
    ]
